tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed": "#e0e3e5",
        "tertiary": "#46494b",
        "inverse-surface": "#283044",
        "on-secondary-fixed": "#001e2f",
        "surface-bright": "#faf8ff",
        "surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#444749",
        "on-surface-variant": "#464555",
        "surface-tint": "#4d44e3",
        "secondary-fixed-dim": "#89ceff",
        "inverse-on-surface": "#eef0ff",
        "on-background": "#131b2e",
        "on-primary-container": "#dad7ff",
        "tertiary-container": "#5e6163",
        "surface-container-highest": "#dae2fd",
        "secondary-fixed": "#c9e6ff",
        "primary": "#3525cd",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "surface-container-low": "#f2f3ff",
        "inverse-primary": "#c3c0ff",
        "surface-container-high": "#e2e7ff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "outline": "#777587",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "primary-container": "#4f46e5",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed-dim": "#c4c7c9",
        "secondary": "#006591",
        "on-surface": "#131b2e",
        "secondary-container": "#39b8fd",
        "on-secondary-fixed-variant": "#004c6e",
        "on-primary": "#ffffff",
        "surface-container": "#eaedff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-container": "#dadcde",
        "background": "#faf8ff",
        "primary-fixed-dim": "#c3c0ff",
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "on-secondary-container": "#004666",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "on-primary-fixed-variant": "#3323cc"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "12px",
        "xs": "4px",
        "md": "24px",
        "lg": "48px",
        "gutter": "24px",
        "base": "8px",
        "xl": "80px",
        "container-max": "1200px"
      },
      "fontFamily": {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Manrope"],
        "headline-md": ["Manrope"],
        "headline-xl": ["Manrope"],
        "body-sm": ["Inter"],
        "headline-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.3", "fontWeight": "700" }]
      }
    }
  }
};
